version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - backend

#  spring-boot-app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    networks:
#      - backend

networks:
  backend:
    driver: bridge
